=== None083/LenguajeMarcas/XML/ejemplos/ejemplo dtd/datos_personales.dtd
<!ELEMENT datos (persona*)>
<!ELEMENT persona (#PCDATA|nombre|direccion|edad)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== None083/LenguajeMarcas/XML/ejemplo dtd/datos_personales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos SYSTEM "datos_personales.dtd">
<datos>
	<persona>
	UWU
		<nombre>Noelia</nombre>
		<direccion>Calle Dolores</direccion>
		<edad>34</edad>
	</persona>
	<persona>
		<nombre>Monty</nombre>
		<direccion>Calle Dolores</direccion>
		<edad>1</edad>
	</persona>
</datos>
