=== None083/LenguajeMarcas/XML/ejemplos/ejemplo 230323/vehiculos.dtd
<!ELEMENT vehiculos (coche, camion, tren, avion, moto)>
<!ENTITY % r_m "ruedas, motor">
<!ELEMENT coche (%r_m;, puertas)>
<!ELEMENT camion (%r_m;, puertas, carga)>
<!ELEMENT tren (%r_m;, vagones)>
<!ELEMENT avion (%r_m;, capacidad)>
<!ELEMENT moto (%r_m;)>
<!ELEMENT ruedas (#PCDATA)>
<!ELEMENT motor (#PCDATA)>
<!ELEMENT puertas (#PCDATA)>
<!ELEMENT carga (#PCDATA)>
<!ELEMENT vagones (#PCDATA)>
<!ELEMENT capacidad (#PCDATA)>

=== None083/LenguajeMarcas/XML/ejemplos/ejemplo 230323/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehiculos SYSTEM "vehiculos.dtd">
<vehiculos>
    <coche>
        <ruedas>4</ruedas>
        <motor>gssfgds</motor>
        <puertas>4</puertas>
    </coche>
    <camion>
        <ruedas>rge</ruedas>
        <motor>gre</motor>
        <puertas>rg</puertas>
        <carga>sg</carga>
    </camion>
    <tren>
        <ruedas>egre</ruedas>
        <motor>rge</motor>
        <vagones>sgrr</vagones>
    </tren>
    <avion>
        <ruedas>rg</ruedas>
        <motor>srg</motor>
        <capacidad>regg</capacidad>
    </avion>
    <moto>
        <ruedas>gerwg</ruedas>
        <motor>regg</motor>
    </moto>
</vehiculos>
