=== None083/LenguajeMarcas/XML/relacionFinal/Ejercicio 16 y 17/buzon_correos.dtd
<!ELEMENT buzon_correos (carta, paquete)*>
<!ENTITY % r_d_c "remitente, destinatario, contenido">
<!ELEMENT carta (%r_d_c;)>
<!ATTLIST carta tipo CDATA #IMPLIED>
<!ELEMENT paquete (%r_d_c;)>
<!ATTLIST paquete tamanio CDATA #IMPLIED>
<!ATTLIST paquete peso CDATA #IMPLIED>
<!ELEMENT remitente EMPTY>
<!ELEMENT destinatario EMPTY>
<!ELEMENT contenido EMPTY>

=== None083/LenguajeMarcas/XML/relacionFinal/Ejercicio 16 y 17/buzon_correos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buzon_correos SYSTEM "buzon_correos.dtd">
<buzon_correos>
    <carta tipo="">
        <remitente></remitente>
        <destinatario></destinatario>
        <contenido></contenido>
    </carta>
    <paquete tamanio="" peso="">
        <remitente></remitente>
        <destinatario></destinatario>
        <contenido></contenido>
    </paquete>
</buzon_correos>
